CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL IDENTITY,
	NOMBRE NVARCHAR(75),
	APELLIDO1 NVARCHAR(50),
	APELLIDO2 NVARCHAR(50),
	EDAD INT,
	CORREO NVARCHAR(50),
	TELEFONO NVARCHAR(20),
	SEXO NVARCHAR(50),
	CEDULA NVARCHAR(20),
	USUARIO NVARCHAR(50),
	PASSWORDS NVARCHAR(100),
	TIPO_USUARIO BIT,
	ESTADO BIT,
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO)

);



CREATE TABLE TECNOLOGIA(
	ID_TECNOLOGIA INT NOT NULL IDENTITY,
	TECNOLOGIA NVARCHAR(150),
	CONSTRAINT PK_TECNOLOGIA PRIMARY KEY(ID_TECNOLOGIA)
);


CREATE TABLE TECNOLOGIA_USUARIO(
	ID_TECNOLOGIA INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	CONSTRAINT PK_TECNOLOGIA_USUARIO PRIMARY KEY(ID_TECNOLOGIA,ID_USUARIO),
	CONSTRAINT FK_TECNOLOGIA_USUARIO FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA(ID_TECNOLOGIA),
	CONSTRAINT FK_USUARIO_TECNOLOGIA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)


);



CREATE TABLE DETALLE(
	ID_DETALLE INT NOT NULL IDENTITY,
	EXPERIENCIA NVARCHAR(200),
	GRADO_ACADEMICO NVARCHAR(100),
	ID_TECNOLOGIA INT,
	CONSTRAINT PK_DETALLE PRIMARY KEY(ID_DETALLE),
	CONSTRAINT FK_DETALLE_TECNOLOGIA FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA(ID_TECNOLOGIA)
);




CREATE TABLE VACANTE(
	ID_VACANTE INT NOT NULL IDENTITY,
	PUESTO NVARCHAR(75),
	HORARIO NVARCHAR(50),
	CONSTRAINT PK_VACANTE PRIMARY KEY(ID_VACANTE)
);



CREATE TABLE VACANTE_TECNOLOGIA(
	ID_TECNOLOGIA INT NOT NULL,
	ID_VACANTE INT NOT NULL,
	CONSTRAINT PK_VACANTE_TECNOLOGIA PRIMARY KEY(ID_TECNOLOGIA,ID_VACANTE),
	CONSTRAINT FK_VACANTE_TECNOLOGIA FOREIGN KEY (ID_VACANTE) REFERENCES VACANTE(ID_VACANTE),
	CONSTRAINT FK_TECNOLOGIA_VACANTE FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA(ID_TECNOLOGIA)
);














