//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRERH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.TECNOLOGIAs = new HashSet<TECNOLOGIA>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string SEXO { get; set; }
        public string CEDULA { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORDS { get; set; }
        public Nullable<bool> TIPO_USUARIO { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECNOLOGIA> TECNOLOGIAs { get; set; }
    }
}
